name: Friday  

on:  
  issue_comment:  
    types: [ created ]  
  pull_request_review:  
    types:  
      - submitted  
  check_suite:  
    types:  
      - completed  

jobs:  
  friday:  
    runs-on: ubuntu-latest  
    env:  
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}  
    steps:  
      - name: Set up Node.js 20  
        uses: actions/setup-node@v3  
        with:  
          node-version: '20'  

      - name: SCM  
        uses: actions/checkout@v3  

      - name: Run assistant  
        uses: maximbircu/pull-request-assistant@latest  
        with:  
          config-path: '.pull-request-assistant.yml'  # Update with your config path  
        env:  
          GITHUB_TOKEN: "${{ secrets.ACCESS_TOKEN }}"

      - name: Run assistant  
        uses: maximbircu/pull-request-assistant@latest  # Update to the latest version  
        env:  
          GITHUB_TOKEN: "${{ secrets.ACCESS_TOKEN }}"
