name: Friday  

on:  
  issue_comment:  
    types: [ created ]  
  pull_request_review:  
    types:  
      - submitted  
  check_suite:  
    types:  
      - completed  

jobs:  
  friday:  
    runs-on: ubuntu-latest  
    env:  
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}  
    steps:  
      - name: Set up Node.js 16  
        uses: actions/setup-node@v2  
        with:  
          node-version: '16'  

      - name: SCM  
        uses: actions/checkout@v2  

      - name: Run assistant  
        uses: maximbircu/pull-request-assistant@1.0.0  

        env:  
          GITHUB_TOKEN: "${{ secrets.ACCESS_TOKEN }}"
